version: "3.9"
services:
  client-service:
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/client
      - /client/node_modules
