# Generated by Django 5.2.5 on 2025-09-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.TextField(default=''),
        ),
    ]
