version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: syedabdullahali/ecommerce-mvp:0.1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://django_user:django_pass@your-db-host:5432/django_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: syedabdullahali/ecommerce-mvp-frontend:0.1
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
