# Generated by Django 5.2.5 on 2025-08-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_mtg_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(default='General', max_length=125),
        ),
    ]
