# Generated by Django 5.2.5 on 2025-09-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_related_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
