# Generated by Django 5.2.5 on 2025-08-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_layout',
            field=models.BooleanField(default=True),
        ),
    ]
