# Generated by Django 5.2.5 on 2025-08-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_show_on_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='show_on_layout',
            field=models.BooleanField(default=False),
        ),
    ]
