# Generated by Django 5.2.5 on 2025-08-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_on_layout',
            field=models.BooleanField(default=True),
        ),
    ]
